[workspace]
resolver = "2"
members = [
    "arci",
    "arci-gamepad-gilrs",
    "arci-gamepad-keyboard",
    "arci-ros",
    "arci-speak-cmd",
    "arci-speak-audio",
    "arci-urdf-viz",
    "openrr",
    "openrr-apps",
    "openrr-client",
    "openrr-command",
    "openrr-config",
    "openrr-gui",
    "openrr-planner",
    "openrr-plugin",
    "openrr-sleep",
    "openrr-teleop",
    "openrr-plugin/examples/plugin",
] # "arci-ros2",

[patch.crates-io]

arci-speak-cmd = { path = "arci-speak-cmd" }
arci-speak-audio = { path = "arci-speak-audio" }
arci = { path = "arci" }
arci-gamepad-gilrs = { path = "arci-gamepad-gilrs" }
arci-gamepad-keyboard = { path = "arci-gamepad-keyboard" }
arci-ros = { path = "arci-ros" }
# arci-ros2 = { path = "arci-ros2" }
arci-urdf-viz = { path = "arci-urdf-viz" }
openrr = { path = "openrr" }
openrr-apps = { path = "openrr-apps" }
openrr-client = { path = "openrr-client" }
openrr-command = { path = "openrr-command" }
openrr-config = { path = "openrr-config" }
openrr-gui = { path = "openrr-gui" }
openrr-planner = { path = "openrr-planner" }
openrr-plugin = { path = "openrr-plugin" }
openrr-sleep = { path = "openrr-sleep" }
openrr-teleop = { path = "openrr-teleop" }
