[package]
name = "openrr-client"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
arci = { version = "0.0.1", path = "../arci" }
async-trait = "0.1"
k = { version = "0.22", features = ["serde-serialize"] }
log = "0.4"
openrr-planner = { version = "0.0.1", path = "../openrr-planner" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
urdf-rs = "0.6"

[dev-dependencies]
assert_approx_eq = "1.1"
regex = "1"
structopt = "0.3"
env_logger = "0.8"
