[package]
name = "openrr-gui"
version = "0.0.5"
authors = ["Taiki Endo <taiki@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr GUI library"
keywords = ["robotics", "robot"]
categories = ["science::robotics", "gui"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/openrr-gui"

[features]
default = ["assimp"]
assimp = ["openrr-client/assimp"]
# Enables the `iced_glow` renderer on GUI.
# This might be useful if the default renderer doesn't work.
glow = ["iced/glow"]

[dependencies]
arci = "0.0.5"
iced = { version = "0.3", features = ["image"] }
openrr-client = { version = "0.0.5", default-features = false }
rand = "0.8"
thiserror = "1"
tracing = { version = "0.1", features = ["log"] }
urdf-rs = "0.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
anyhow = "1"
# openrr-apps = { version = "0.0.5", default-features = false }
structopt = "0.3"
tracing-subscriber = "0.2"
arci-urdf-viz = { version = "0.0.5", default-features = false }
serde = { version = "1", features = ["derive"] }
toml = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
